---
name: test
on:
  pull_request:
  push:
    branches:
    - gh-readonly-queue/**
    - master
jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        go:
        - "1.20"
        - "1.19"
        - "1.18"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - run: go test -v -cover ./...
      timeout-minutes: 10
      env:
        TF_ACC: "1"
